// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnyIt3jo72sginWR4R6ni4qhKlS67xQ7M',
    appId: '1:655575590413:web:5f75b751772f74b9165744',
    messagingSenderId: '655575590413',
    projectId: 'collect-the-world-429522',
    authDomain: 'collect-the-world-429522.firebaseapp.com',
    storageBucket: 'collect-the-world-429522.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWsUyXblHp9Bpmep0Tk2vlZkNMKhjRm8',
    appId: '1:655575590413:android:d9cc26bfe6ef1b0d165744',
    messagingSenderId: '655575590413',
    projectId: 'collect-the-world-429522',
    storageBucket: 'collect-the-world-429522.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9UYh8FhGJb0q4TtLKEaqXcQzdV3_olfg',
    appId: '1:655575590413:ios:97c7137c9087d7e3165744',
    messagingSenderId: '655575590413',
    projectId: 'collect-the-world-429522',
    storageBucket: 'collect-the-world-429522.appspot.com',
    androidClientId: '655575590413-kke7ii4fdb7o2gve3nuvvc6dkd1aasrb.apps.googleusercontent.com',
    iosBundleId: 'com.CTW.name',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9UYh8FhGJb0q4TtLKEaqXcQzdV3_olfg',
    appId: '1:655575590413:ios:a0e766e61ca1535f165744',
    messagingSenderId: '655575590413',
    projectId: 'collect-the-world-429522',
    storageBucket: 'collect-the-world-429522.appspot.com',
    androidClientId: '655575590413-kke7ii4fdb7o2gve3nuvvc6dkd1aasrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.collectTheWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnyIt3jo72sginWR4R6ni4qhKlS67xQ7M',
    appId: '1:655575590413:web:228b8bc99aecbf5d165744',
    messagingSenderId: '655575590413',
    projectId: 'collect-the-world-429522',
    authDomain: 'collect-the-world-429522.firebaseapp.com',
    storageBucket: 'collect-the-world-429522.appspot.com',
  );

}